name: PR Validation

on:
  issue_comment:
    types:
      - created

jobs:
  validate:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '+1'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Build
        run: npm run build